// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrKbXdBXkhiKCpFEqcy-D6T0aC_S8EXgY',
    appId: '1:801528647712:web:a88113ffba0bdbf9136c45',
    messagingSenderId: '801528647712',
    projectId: 'lapor-book-46b2e',
    authDomain: 'lapor-book-46b2e.firebaseapp.com',
    storageBucket: 'lapor-book-46b2e.appspot.com',
    measurementId: 'G-BDT3BRCCNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoJkPxDyuo3p_5p4aQYxqdiwtCn-BJPFg',
    appId: '1:801528647712:android:9ad2a91af46a6ded136c45',
    messagingSenderId: '801528647712',
    projectId: 'lapor-book-46b2e',
    storageBucket: 'lapor-book-46b2e.appspot.com',
  );
}
